#!/bin/bash
#SBATCH --chdir /home/herlevi
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 8G
#SBATCH --partition gpu
#SBATCH --gres gpu:1
#SBATCH --qos dlav
#SBATCH --account civil-459-2023

module load gcc/8.4.0-cuda cuda/11.1.1
source projekti/bin/activate
which python3
which projekti/bin/python3
nvidia-smi

projekti/bin/python3 monodepth2/train.py