#!/bin/bash
#SBATCH --chdir /home/herlevi
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 4
#SBATCH --mem 16G
#SBATCH --partition gpu
#SBATCH --gres gpu:1
#SBATCH --qos dlav
#SBATCH --account civil-459-2023
#SBATCH --time=00:05:00

module load gcc/8.4.0-cuda cuda/11.1.1
source projekti/bin/activate
nvidia-smi

projekti/bin/python3 monodepth2/train.py